CREATE DATABASE carpp;

USE carpp;

CREATE TABLE cars( 
id INT NOT NULL AUTO_INCREMENT PRIMARY KEY, 
brand VARCHAR(100) NOT NULL,
color VARCHAR(100) NOT NULL,
releaseYear INT NOT NULL,
propulsionType VARCHAR(100) NOT NULL
 );